baseURL = 'https://mozes-y.github.io/'
languageCode = 'zh-CN'
title = "Mozes's Blog"
theme = 'FixIt'
defaultContentLanguage = 'zh-cn'
[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"
  category = 'categories'
  tag = 'tags'
